# Generated by Django 4.0.6 on 2022-07-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='city',
            field=models.TextField(),
        ),
    ]
